name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  APP_NAME: yougo-ui
  REGISTRY: quay.io/${{ github.repository_owner }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Node cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Formatting
        run: npm run format:check

  #      - name: Unit tests
  #        run: npm test

  publish:
    name: Build & publish container image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Container Image
        id: build-image
        uses: redhat-actions/buildah-build@v2.5
        with:
          image: ${{ env.APP_NAME }}
          dockerfiles: Dockerfile

      - name: Publish Container Image
        uses: redhat-actions/push-to-registry@v2
        if: github.ref == 'refs/heads/main'
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

  deploy:
    name: Deploy to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Node cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.API_URL }}
          REACT_APP_OIDC_AUTHORITY: ${{ secrets.OIDC_AUTHORITY }}
          REACT_APP_OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}

      - name: Deploy to GitHub Pages ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: build
          single-commit: true
